services:
    zipou_system.initservice:
        class: box4b\SystemBundle\Services\InitService
        arguments: ["@logger", "@event_dispatcher"]

    zipou_system.cronservice:
        class: box4b\SystemBundle\Services\CronService
        arguments: ["@logger", "@event_dispatcher"]

    zipou_system.threadservice:
        class: box4b\SystemBundle\Services\ThreadService
        arguments: ["@logger", "@doctrine", "%kernel.root_dir%"]
        tags:
            - { name: kernel.event_subscriber }
